install ant
install astyle
install autoconf
install automake
install bison
install boost
install brew-cask
install cairo
install cloc
install cloog018
install colordiff
install cscope
install ctags
install czmq
install dirmngr
install ffmpeg
install fish
install flac
install fontconfig
install fontforge
install freetype
install gcc48
install gdbm
install gettext
install ghostscript
install gifsicle
install gist
install git
install git-flow
install glib
install gmp
install gmp4
install gnu-tar
install gnupg2
install go
install gobject-introspection
install gpg-agent
install harfbuzz
install htop-osx
install icu4c
install imagemagick
install isl011
install jbig2dec
install jpeg
install jq
install lame
install lesstif
install libassuan
install libebml
install libevent
install libffi
install libgcrypt
install libgpg-error
install libksba
install libmagic
install libmatroska
install libmpc08
install libogg
install libpng
install libsodium
install libtiff
install libtool
install libusb
install libusb-compat
install libvo-aacenc
install libvorbis
install libyaml
install little-cms2
install logrotate
install lua
install lv
install makedepend
install maven
install mercurial
install mkvtoolnix
install mpfr2
install ngrep
install nkf
install nmap
install node
install openssl
install pandoc
install pango
install pcre
install pinentry
install pixman
install pkg-config
install popt
install pstree
install pth
install python
install readline
install reattach-to-user-namespace
install rsense
install rtmpdump
install ruby
install scons
install spark
install sqlite
install ssh-copy-id
install subversion
install tmux
install tree
install vim
install watch
install wget
install x264
install xpdf
install xvid
install xz
install zeromq
install zsh
cask install mactex
cask install wireshark
cask install xquartz
