install astyle
install autoconf
install automake
install bison
install brew-cask
install cairo
install cloog018
install colordiff
install cscope
install czmq
install dirmngr
install fontconfig
install fontforge
install freetype
install gcc48
install gdbm
install gettext
install gist
install git
install git-flow
install glib
install gmp4
install gnu-tar
install gnupg2
install go
install gobject-introspection
install gpg-agent
install harfbuzz
install htop-osx
install icu4c
install isl011
install jpeg
install jq
install libassuan
install libevent
install libffi
install libgcrypt
install libgpg-error
install libksba
install libmpc08
install libpng
install libsodium
install libtiff
install libtool
install libusb
install libusb-compat
install libyaml
install lua
install lv
install mercurial
install mpfr2
install ngrep
install nkf
install openssl
install pango
install pcre
install pinentry
install pixman
install pkg-config
install pstree
install pth
install python
install readline
install reattach-to-user-namespace
install sqlite
install tmux
install tree
install vim
install watch
install wget
install zeromq
install zsh
cask install eclipse-java
cask install xquartz
