install aalib
install ant
install arp-scan
install arping
install aspell
install astyle
install atk
install autoconf
install automake
install autossh
install babl
install bison
install boost
install brew-cask
install bwm-ng
install cairo
install ccat
install cloc
install cloog018
install cmake
install colordiff
install coreutils
install cscope
install ctags
install czmq
install d-bus
install dirmngr
install faac
install ffmpeg
install fish
install flac
install fontconfig
install fontforge
install freetype
install gawk
install gcc48
install gd
install gdbm
install gdk-pixbuf
install gegl02
install gettext
install ghostscript
install gifsicle
install gimp
install gist
install git
install git-flow
install glib
install gmp
install gmp4
install gnu-tar
install gnupg2
install gnuplot
install go
install gobject-introspection
install gpg-agent
install gsettings-desktop-schemas
install gtk+
install gtk+3
install gtk-mac-integration
install harfbuzz
install hicolor-icon-theme
install htop-osx
install icu4c
install imagemagick
install isl011
install jbig2dec
install jhead
install jpeg
install jq
install lame
install lesstif
install libassuan
install libcroco
install libebml
install libepoxy
install libevent
install libffi
install libgcrypt
install libgpg-error
install libksba
install libmagic
install libmatroska
install libmpc08
install libnet
install libogg
install libpng
install librsvg
install libsodium
install libtiff
install libtool
install libusb
install libusb-compat
install libvo-aacenc
install libvorbis
install libwmf
install libyaml
install little-cms2
install logrotate
install lsyncd
install lua
install lv
install makedepend
install maven
install mercurial
install mkvtoolnix
install mpfr2
install ngrep
install nkf
install nmap
install node
install oniguruma
install openmotif
install openssl
install pandoc
install pango
install pcre
install pinentry
install pixman
install pkg-config
install popt
install pstree
install pth
install py2cairo
install pygobject
install pygtk
install python
install qt
install readline
install reattach-to-user-namespace
install rsense
install rtmpdump
install ruby
install scons
install simstring
install spark
install sqlite
install ssh-copy-id
install subversion
install texi2html
install the_silver_searcher
install tidy-html5
install tmux
install tree
install vim
install watch
install wget
install x264
install xpdf
install xvid
install xz
install yasm
install zeromq
install zsh
cask install handbrake
cask install kaleidoscope
cask install ksdiff
cask install mactex
cask install osxfuse
cask install shapes
cask install sshfs
cask install vagrant
cask install vagrant-manager
cask install virtualbox
cask install wireshark
cask install xquartz
