#!/usr/bin/env zsh

skip_global_compinit=1

ZDOTDIR=${XDG_CONFIG_HOME:=~/.config}/zsh

# extended globbing
setopt EXTENDED_GLOB
# don't source /etc/z*
setopt NO_GLOBAL_RCS

(( ${+TERM} )) || export TERM="xterm-256color"; COLORTERM="truecolor"
(( ${+USER} )) || export USER="${USERNAME}"
(( ${+XDG_CACHE_HOME} )) || export XDG_CACHE_HOME="${HOME}/.cache"
(( ${+XDG_CONFIG_HOME} )) || export XDG_CONFIG_HOME="${HOME}/.config"
(( ${+XDG_DATA_HOME} )) || export XDG_DATA_HOME="${HOME}/.local/share"

# Editor
export EDITOR=nvim
export VISUAL=nvim

# Pager
export PAGER=most

# Program options
export \
    ANSIBLE_SCP_IF_SSH=y \
    COMPOSE_DOCKER_CLI_BUILD=1 \
    CORRECT_IGNORE="*zinit[-]*" \
    DISABLE_MAGIC_FUNCTIONS=1 \
    DOCKER_BUILDKIT=1 \
    GTAGSLABEL=pygments \
    HOMEBREW_NO_{ENV_HINTS,INSTALL_CLEANUP}=1 \
    OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES \
    RIPGREP_CONFIG_PATH=${XDG_CONFIG_HOME}/ripgrep/rc \
    SHELL_SESSIONS_DISABLE=1
# $PATH and $path (and also $FPATH and $fpath, etc.) are "tied" to each other.
# Modifying one will also modify the other.
# Note that each value in an array is expanded separately. Thus, we can use ~
# for $HOME in each $path entry.
typeset -gU FPATH PATH fpath path
# path=( /{opt,usr/local}/Homebrew/bin(N) /home/linuxbrew/.linuxbrew/bin(N) $path )
fpath=( ~/.config/zsh/(func|comple)tions(N) $fpath )
autoload -Uz ~/.config/zsh/functions/**/*

path=(
    /usr/local/bin(N-/)
    /usr/bin(N-/)
    /bin(N-/)
    /usr/local/sbin(N-/)
    /usr/sbin(N-/)
    /sbin(N-/)
    /usr/X11/bin(N-/)
)
fpath=(
    ~/.zsh/completions(N-/)
    $fpath
)
