[tools]
act = "0.2.89"
antigravity-cli = "latest"
bat = "latest"
bat-extras = "latest"
delta = "latest"
deno = "2.8.3"
direnv = "latest"
duf = "latest"
dust = "latest"
fd = "latest"
fzf = "latest"
eza = "latest"
gh = "2.95.0"
ghq = "latest"
golang = "1.26.1"
goreleaser = "2.16.0"
hyperfine = "latest"
just = "1.52.0"
lua = "5.4.8"
maven = "3.9.16"
neovim = "0.12.3"
nodejs = "24.14.1"
"npm:@bitwarden/cli" = "2026.5.0"
pipx = "1.14.1"
pnpm = "10.32.0"
poetry = "2.4.1"
python = "3.14.6"
ripgrep = "latest"
ruby = "3.4.9"
starship = "latest"
topgrade = "latest"
tree-sitter = "0.26.9"
uv = "latest"
zellij = "latest"
