#!/usr/bin/env zsh

#------------------------------------
# start zprof
[[ -z "$ZPROF" ]] || zmodload zsh/zprof
#------------------------------------
# zproftime
## diagnose afterward: `zproftime-sort /tmp/zproftime.* | head`
if [[ -n "${ENABLE_ZPROFTIME}" ]]; then
    zmodload zsh/datetime
    setopt PROMPT_SUBST
    PS4='+$EPOCHREALTIME %N:%i> '
    logfile=$(mktemp /tmp/zproftime.XXXX)
    exec 3>&2 2>$logfile
    setopt XTRACE
fi
#------------------------------------

#0="${${ZERO:-${0:#$ZSH_ARGZERO}}:-${(%):-%N}}"
#0="${${(M)0:#/*}:-$PWD/$0}"
#print -- "${0:h}"
#local ZDOTDIR="${0:h}"
local ZDOTDIR=${XDG_CONFIG_HOME:=~/.config}/zsh
for f in ${ZDOTDIR}/rc.d/<->-*zsh(N); do
    source "$f"
    #print -- "$f"
done

#------------------------------------
# zproftime end
if [[ -n "${ENABLE_ZPROFTIME}" ]]; then
    unsetopt XTRACE
    exec 2>&3 3>&-
fi
#------------------------------------
# end zprof
[[ -z "$ZPROF" ]] || zprof | $PAGER
#------------------------------------

############### -------------

# source local
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local
[[ -s ~/.profile ]] && source ~/.profile
[[ -s ~/.login ]] && source ~/.login

# for classic prompt
autoload -U colors && colors
colors=(
    $'%{\e[38;5;3m%}'   # yellow
    $'%{\e[38;5;9m%}'   # brown red
    $'%{\e[38;5;6m%}'   # cyan
    $'%{\e[38;5;5m%}'   # magenta
    $'%{\e[38;5;4m%}'   # blue
    $'%{\e[38;5;111m%}' # pale purple
    $'%{\e[38;5;27m%}'  # ocean blue
    $'%{\e[38;5;129m%}' # purple
    $'%{\e[38;5;1m%}'   # red
    $'%{\e[38;5;2m%}'   # green
    $'%{\e[38;5;113m%}' # lime green
)

case ${OSTYPE} in
    darwin*)
        # starship
        command -v starship &> /dev/null && eval "$(starship init zsh)"
        ;;
    linux*)
        colored_time=%{$fg[cyan]%}%T
        colored_user=$colors[$((`echo "$USER" | sum | cut -f1 -d' '`%${#colors}))+1]$USER
        colored_at=%{$fg[white]%}@
        host_name=`hostname | cut -d. -f1`
        colored_host=$colors[$((`echo "$host_name" | sum | cut -f1 -d' '`%${#colors}))+1]$host_name
        #colored_host=%{$fg[blue]%}$host_name
        colored_colon=%{$reset_color%}:
        colored_path=%{$fg[magenta]%}%~
        #colored_prompt=%{$reset_color%}%#
        newline=$'\n'
        PROMPT="${colored_time} ${colored_user}${colored_at}${colored_host}${colored_colon}${PROMPT/ /"$newline"}"
        ;;
esac

# Attach tmux on login
#if [ ! -z `which tmux` ]; then
#  if [ $SHLVL = 1 ]; then
#    if [ $(( `ps aux | grep tmux | grep $USER | grep -v grep | wc -l` )) != 0 ]; then
#      echo -n 'Attach tmux session? [Y/n]'
#      read YN
#      [[ $YN = '' ]] && YN=y
#      [[ $YN = y ]] && tmux attach
#    #else
#    #  tmux
#    fi
#  fi
#fi
