#!/usr/bin/env zsh

#------------------------------------
# start zprof
[[ -z "$ZPROF" ]] || zmodload zsh/zprof
#------------------------------------
# zproftime
## diagnose afterward: `zproftime-sort /tmp/zproftime.* | head`
if [[ -n "${ENABLE_ZPROFTIME}" ]]; then
    zmodload zsh/datetime
    setopt PROMPT_SUBST
    PS4='+$EPOCHREALTIME %N:%i> '
    logfile=$(mktemp /tmp/zproftime.XXXX)
    exec 3>&2 2>$logfile
    setopt XTRACE
fi
#------------------------------------

# rc.d
local ZDOTDIR=${XDG_CONFIG_HOME}/zsh
for f in ${ZDOTDIR}/rc.d/<->-*zsh(N); do
    #print -- "$f"
    source "$f"
done

# Editor
if command nvim --version > /dev/null 2>&1; then
    export EDITOR=nvim
    export VISUAL=nvim
elif whence vim > /dev/null; then
    export EDITOR=vim
    export VISUAL=vim
fi

# Pager
export PAGER=less
#export PAGER=most

#------------------------------------
# zproftime end
if [[ -n "${ENABLE_ZPROFTIME}" ]]; then
    unsetopt XTRACE
    exec 2>&3 3>&-
fi
#------------------------------------
# end zprof
[[ -z "$ZPROF" ]] || zprof | $PAGER
#------------------------------------

############### -------------

# source local if non-empty files exist (should not be managed by chezmoi)
[[ -s ~/.zprofile ]] && source ~/.zprofile
