add_newline = true
continuation_prompt = '▶▶ '

# Use custom format
format = "$all$character"

[directory]
truncation_length = 10
truncate_to_repo = false

[hostname]
format = "@[$hostname]($style):"
style = "bold bright-blue"
ssh_only = false

[time]
disabled = false
format = "[$time]($style) "

[username]
format = "[$user]($style)"
style_user = "bold red"
show_always = true
